---
name: Tests

on:
  push:
    branches:
      - '*'
  pull_request:
    branches: [master]

jobs:
  build:

    strategy:
      matrix:
        node-version: [18, 20, 22]
        platform: [ubuntu-latest]

    runs-on: ${{ matrix.platform }}

    env:
      OS: ${{ matrix.os }}
      NODE: ${{ matrix.node-version }}
    steps:
      - uses: actions/checkout@v4
      - name: Install pnpm
        run: corepack enable
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install
      - run: npm run build
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
